package com.ryan_mtg.servobot.commands;

import com.ryan_mtg.servobot.commands.chat.AddCommand;
import com.ryan_mtg.servobot.commands.chat.AddReactionCommand;
import com.ryan_mtg.servobot.commands.chat.DeleteCommand;
import com.ryan_mtg.servobot.commands.chat.FactsCommand;
import com.ryan_mtg.servobot.commands.chat.MessageChannelCommand;
import com.ryan_mtg.servobot.commands.chat.TextCommand;
import com.ryan_mtg.servobot.commands.chat_draft.EnterChatDraftCommand;
import com.ryan_mtg.servobot.commands.chat_draft.OpenChatDraftCommand;
import com.ryan_mtg.servobot.commands.game.GameCommand;
import com.ryan_mtg.servobot.commands.game.JoinGameCommand;
import com.ryan_mtg.servobot.commands.game_queue.GameQueueCommand;
import com.ryan_mtg.servobot.commands.game_queue.JoinGameQueueCommand;
import com.ryan_mtg.servobot.commands.game_queue.RemoveFromGameQueueCommand;
import com.ryan_mtg.servobot.commands.game_queue.ShowGameQueueCommand;
import com.ryan_mtg.servobot.commands.giveaway.EnterRaffleCommand;
import com.ryan_mtg.servobot.commands.giveaway.RaffleStatusCommand;
import com.ryan_mtg.servobot.commands.giveaway.RequestPrizeCommand;
import com.ryan_mtg.servobot.commands.giveaway.SelectWinnerCommand;
import com.ryan_mtg.servobot.commands.giveaway.StartRaffleCommand;
import com.ryan_mtg.servobot.commands.magic.CardSearchCommand;
import com.ryan_mtg.servobot.commands.magic.ScryfallSearchCommand;
import com.ryan_mtg.servobot.commands.roles.MakeRoleMessageCommand;
import com.ryan_mtg.servobot.commands.roles.SetRoleCommand;
import com.ryan_mtg.servobot.commands.roles.SetUsersRoleCommand;

public interface CommandVisitor {
    void visitAddBookedStatementCommand(AddBookedStatementCommand addBookedStatementCommand);
    void visitAddCommand(AddCommand addCommand);
    void visitAddReactionCommand(AddReactionCommand addReactionCommand);
    void visitAddStatementCommand(AddStatementCommand addStatementCommand);
    void visitCardSearchCommand(CardSearchCommand cardSearchCommand);
    void visitDelayedAlertCommand(DelayedAlertCommand delayedAlertCommand);
    void visitDeleteCommand(DeleteCommand deleteCommand);
    void visitEnterChatDraftCommand(EnterChatDraftCommand enterChatDraftCommand);
    void visitEnterRaffleCommand(EnterRaffleCommand enterRaffleCommand);
    void visitEvaluateExpressionCommand(EvaluateExpressionCommand evaluateExpressionCommand);
    void visitFactsCommand(FactsCommand factsCommand);
    void visitGameCommand(GameCommand gameCommand);
    void visitGameQueueCommand(GameQueueCommand gameQueueCommand);
    void visitGiveawayStatusCommand(RaffleStatusCommand raffleStatusCommand);
    void visitJoinGameCommand(JoinGameCommand joinGameCommand);
    void visitJoinGameQueueCommand(JoinGameQueueCommand joinGameQueueCommand);
    void visitMakeRoleMessageCommand(MakeRoleMessageCommand makeRoleMessageCommand);
    void visitMessageChannelCommand(MessageChannelCommand messageChannelCommand);
    void visitOpenChatDraftCommand(OpenChatDraftCommand openChatDraftCommand);
    void visitRemoveFromGameQueueCommand(RemoveFromGameQueueCommand removeFromGameQueueCommand);
    void visitRequestPrizeCommand(RequestPrizeCommand requestPrizeCommand);
    void visitScryfallSearchCommand(ScryfallSearchCommand scryfallSearchCommand);
    void visitScoreCommand(ScoreCommand scoreCommand);
    void visitSelectWinnerCommand(SelectWinnerCommand selectWinnerCommand);
    void visitSetArenaUsernameCommand(SetArenaUsernameCommand setArenaUsernameCommand);
    void visitSetRoleCommand(SetRoleCommand setRoleCommand);
    void visitSetStatusCommand(SetStatusCommand setStatusCommand);
    void visitSetUsersRoleCommand(SetUsersRoleCommand setUsersRoleCommand);
    void visitSetValueCommand(SetValueCommand setValueCommand);
    void visitShowArenaUsernamesCommand(ShowArenaUsernamesCommand showArenaUsernamesCommand);
    void visitShowGameQueueCommand(ShowGameQueueCommand showGameQueueCommand);
    void visitShowValueCommand(ShowValueCommand showValueCommand);
    void visitStartGiveawayCommand(StartRaffleCommand startRaffleCommand);
    void visitTextCommand(TextCommand textCommand);
    void visitTierCommand(TierCommand tierCommand);
}
